[theme]
[server]
fileWatcherType = "poll"                # avoid inotify
folderWatchBlacklist = [
  ".git", "venv", "env", ".venv",       # virtualenv + git
  "__pycache__", ".cache",               # caches
  "models", "data", "datasets",          # large dirs in your repo (adjust as needed)
  "node_modules"
]
headless = true

[theme]
base="light"
primaryColor="#5E7A61"
backgroundColor="#F8F6F0"
secondaryBackgroundColor="#E7E3D4"
textColor="#3A3A3A"
font="serif"

[global]
hideTopBar=false
